### ISSUE TITLE
this.notification is not defined

### ISSUE THREAD

**Issue by christophediprima** [arturcarvalho/at-beach#1]
Hey Artur! I am having a look at your project and noticed that you are using ```this.notification``` in stead of ```this.clearNotification``` on this line :

https://github.com/arturcarvalho/at-beach/blob/3c9eb323e0cdd64fb9f39a3b92635aaa534bfe4e/src/App.js#L78

Yet your demo is working so maybe you forgot to push your last changes?

**Comment by arturcarvalho** [comment]
Hi Christophe and thanks for the heads up!

I indeed fat-finger clicked in the notifications and removed the email notification. 🤦‍♂ 

But I don't think this was the problem you had installing with npm. I've developed on my windows machine and I had no issue. I git cloned it and installed it also without no issue.

But when I tried the install on my mac, it blew up. 

I checked the npm logs and it was the websocket-driver causing issues. I removed the package-lock.json and `npm i` again and it worked. 

> Can you try removing package-lock.json and installing again and see if it works?

I don't know how CRA added the 1.7.2 version of websocket-drive on my win machine if it's not even on npm published versions:

![image](https://user-images.githubusercontent.com/2487710/60248798-ad986080-98c3-11e9-909f-2b851c86ef7f.png)

Quick question, how did you find out the unused method?
